### ISSUE TITLE
Horovod test sometimes fell

### ISSUE THREAD

**Issue by NicoRenaud** [NLESC-JCER/QMCTorch#90]
It appears that the test for horovod sometimes fail because multiple processes try to create the hdf5 file of Molecule. 
```
E   OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

h5py/h5f.pyx:96: OSError

During handling of the above exception, another exception occurred:

self = <horovod_tests.test_solver_orbital_horovod.TestSolverOribitalHorovod testMethod=test_single_point>

    def setUp(self):
        hvd.init()
    
        torch.manual_seed(101)
        np.random.seed(101)
    
        set_torch_double_precision()
    
        # molecule
>       mol = Molecule(atom='H 0 0 -0.69; H 0 0 0.69',
                       calculator='pyscf', basis='sto-3g',
                       unit='bohr', rank=hvd.local_rank())

horovod_tests/test_solver_orbital_horovod.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
qmctorch/scf/molecule.py:115: in __init__
    dump_to_hdf5(self, self.hdf5file,
qmctorch/utils/hdf5_utils.py:143: in dump_to_hdf5
    h5 = h5py.File(fname, 'a')
../anaconda3/envs/qmctorch/lib/python3.8/site-packages/h5py/_hl/files.py:424: in __init__
    fid = make_fid(name, mode, userblock_size,
../anaconda3/envs/qmctorch/lib/python3.8/site-packages/h5py/_hl/files.py:204: in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   OSError: Unable to create file (unable to open file: name = 'H2_pyscf_sto-3g.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

h5py/h5f.pyx:116: OSError
```
We might have to check that if we have multiple process only the rank=0 creates the molecule or something on those lines ...

**Comment by matthijsdewit111** [comment]
Trying to fix this on branch [horovod_integration](https://github.com/NLESC-JCER/QMCTorch/tree/horovod_integration).

The way pytest was run for the horovod tests was wrong, instead of ``pytest -n 2 test_dir [options]`` it should have been ``mpirun -np 2 pytest test_dir [options]``.

Previously it spawned two processes in parallel with both rank 0 therefore they were both trying to write to the same file (as the process with rank 0 does this). With mpirun it correctly makes one process with rank 0 and another with rank 1.

Now that MPI/horovod correctly uses multiple threads, pytest is run in parallel entirely (or something like that), which means that it has to produce coverage data in different files to prevent wring to the same file. This is done by setting ``[coverage:run] parallel=True`` in theory. This will create ``.coverage.[unique-post-fix]`` files, which then can all be combined into 1 ``.coverage`` file.

This works sometimes, [success example](https://github.com/NLESC-JCER/QMCTorch/actions/runs/676342364), however this seems to be non-deterministic [failed example](https://github.com/NLESC-JCER/QMCTorch/actions/runs/676686600).

It seems to produce empty .coverage files, but only sometimes?? Haven't found a solution to this issue yet.

**Comment by matthijsdewit111** [comment]
Update: Apparently pytest-cov automatically combines coverage files at the end of the tests, so when run with ``mpirun -np 2 pytest test_dir --cov`` it creates two coverage instances for each process that merge *ALL* .coverage files after their respective process has finished, including the ones from the other process that still might be writing to coverage files.

Therefore we need to wait for both processes to be finished, so instead of running pytest with pytest-cov to generate coverage , we have to run the tests as follows: ``coverage run -m pytest test_dir``. (again with ``[coverage:run] parallel=True``)  
This doesn't combine the reports at the end, so after the whole reporting is done, we run ``coverage combine`` to combine the results in one .coverage file.

**Comment by NicoRenaud** [comment]
I think we are done with that :)
